/*--------- START TESTS ---------*/

const assert = require("assert");

test("this test passes", async () => {
  assert(true === true, "true is true");
});

test("this test fails", async () => {
  assert(true === false, "true isn't false");
});

/*--------- END TESTS ---------*/

/** run tests - generated by http://npmjs.com/tinit */
function test(text, func) { (test.all = test.all || []).push({ i: test.all.length, text, func }); }
(async () => { // autorun
  const log = (msg, c) => process.stdout.write((["\033[32m", "\033[31m"][c] || "") + msg + "\033[0m");
  log("tinit running " + test.all.length + " tests...\n");
  while ((t = test.all.shift())) {
    log(" > " + (t.i + 1) + ". " + t.text + "...");
    try { await t.func(); } catch (e) {
      log("FAIL\n" + (e && e.stack || e) + "\n", 1);
      process.exit(1);
    };
    log("PASS\n", 0);
  }
  process.exit(0);
})();